server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 2048

myApplicationName: "prod active"

spring:
  # profiles:
  #  active: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://jktdb-dev.gkewang.cn:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: dev_jkt
      password: "!@#$qwer"

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.fish.myspringboot.entity
#  configuration:
#    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.fish.myspringboot.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# debug: true
trace: true
# 默认所有日志都打印在控制台，如果要打印文件中的日志，需要配置 logging.file 或 logging.path
logging:
  file:
    path: log/tmp/

