server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 2048

spring:
  # profiles:
  #  active: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.4.30:9033/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: username
      password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fish.myspringboot.pojo

#debug: true
trace: true
logging:
  file:
    name: my.log
